### ISSUE TITLE
Does not work with Py 3.4, recursive import in __init__.py

### ISSUE THREAD

**Issue by bjodah** [kjellmf/dot2tex#48]
```
$ pip3 install --user --upgrade dot2tex
$ python3
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dot2tex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bjorn/.local/lib/python3.4/site-packages/dot2tex/__init__.py", line 36, in <module>
    __version__ = d2t.__version__
AttributeError: 'module' object has no attribute '__version__'
```

Looking at `__init__.py` I get confused by the import of dot2tex.

**Comment by kjellmf** [comment]
Dot2tex is not compatible with Python 3.x yet.

**Comment by bjodah** [comment]
Ah, I see. Thank you for the information.

**Comment by carlthome** [comment]
Status?

**Comment by ScumCoder** [comment]
Hey,

I have several versions of `python` installed on my OpenSuSE, and I made sure that 2.7 is the default:
```
# file /usr/bin/python
/usr/bin/python: symbolic link to `python2.7'
# python -V
Python 2.7.8
```
However, when I run `dot2tex` it automatically loads version `3.4` and promptly crashes. Any advice on this? Thanks.

**Comment by ScumCoder** [comment]
Never mind, I tried to install `dot2tex` using the downloaded *.tar.gz and `python setup.py install`, and everything works now.

**Comment by folex** [comment]
experienced this on macOS 10.13.6, Python 3.7.0 after installing via `pip install dot2tex`:
```
$ dot2tex
Traceback (most recent call last):
  File "/usr/local/bin/dot2tex", line 7, in <module>
    from dot2tex.dot2tex import main
  File "/usr/local/lib/python3.7/site-packages/dot2tex/__init__.py", line 36, in <module>
    __version__ = d2t.__version__
AttributeError: module 'dot2tex' has no attribute '__version__'
```

**Comment by tscrim** [comment]
See PR #68.

**Comment by kjellmf** [comment]
Fixed in PR #68
